"""
Build two within-group combination_search notebooks:
  - combination_search_snackpacks.ipynb
  - combination_search_drinks.ipynb

Both notebooks mirror the depth of combination_search.ipynb but operate inside a
single 5-product group, dropping cross-group sections and adding within-group
sections (PCA factor structure, composite-index residuals, lead-lag, rolling
correlation stability) that surface edge once the dominant common factor is
removed.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

GROUPS = {
    "snackpacks": {
        "title": "Snackpacks",
        "products": [
            "SNACKPACK_CHOCOLATE",
            "SNACKPACK_VANILLA",
            "SNACKPACK_PISTACHIO",
            "SNACKPACK_STRAWBERRY",
            "SNACKPACK_RASPBERRY",
        ],
        "out_dir": "combination_search_snackpacks_outputs",
        "filename": "combination_search_snackpacks.ipynb",
    },
    "oxygen_shakes": {
        "title": "Drinks (Oxygen Shakes)",
        "products": [
            "OXYGEN_SHAKE_MORNING_BREATH",
            "OXYGEN_SHAKE_EVENING_BREATH",
            "OXYGEN_SHAKE_MINT",
            "OXYGEN_SHAKE_CHOCOLATE",
            "OXYGEN_SHAKE_GARLIC",
        ],
        "out_dir": "combination_search_drinks_outputs",
        "filename": "combination_search_drinks.ipynb",
    },
}


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def code(*lines):
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": list(lines),
    }


def build_cells(group_key: str, cfg: dict) -> list:
    title = cfg["title"]
    products = cfg["products"]
    out_dir = cfg["out_dir"]
    products_repr = "[\n    " + ",\n    ".join(f'"{p}"' for p in products) + ",\n]"

    cells = []

    # ---- Cell 0: install ----
    cells.append(code(
        "# Run once on first open. Skip / comment out after the first successful run.\n",
        "!pip3 install --quiet numpy pandas matplotlib seaborn plotly statsmodels scikit-learn\n",
    ))

    # ---- §0 Title ----
    cells.append(md(
        f"# Round 5 — Within-Group Combinatorial Search: **{title}**\n",
        "\n",
        f"This notebook is a focused, in-depth correlation / cointegration search **inside a single 5-product group** ({title}). It mirrors `combination_search.ipynb` but is restricted to one group, and adds within-group sections that are only meaningful when products are expected to share a strong common factor.\n",
        "\n",
        "## Why a within-group notebook?\n",
        "\n",
        "All 5 variants of the same item are very likely to share a single dominant factor (raw-material cost, demand for the category, etc.). Cross-group analysis is almost guaranteed to surface that factor as ‘structural’ correlation. The interesting question inside a group is the **opposite**:\n",
        "\n",
        "> *After removing the common factor, do any pairs / baskets in this group still mean-revert?*\n",
        "\n",
        "Edges of that form are pure relative-value trades inside the group, and they tend to be much cleaner than cross-group trades because the products share market microstructure (same ticks, same liquidity profile, same observers).\n",
        "\n",
        "## Search ladder\n",
        "\n",
        "| § | Search | What we find |\n",
        "|---|---|---|\n",
        "| §2 | Data load + raw price viz | sanity, regime shifts |\n",
        "| §3 | Pearson + Spearman + Kendall — all 1↔1 | which products co-move (level + returns + ranks) |\n",
        "| §4 | Rolling correlation stability | does the relationship hold across days? |\n",
        "| §5 | Lead-lag cross-correlation | which product moves first |\n",
        "| §6 | 1↔1 cointegration (all 10 pairs) | best raw pairs by EG / ADF |\n",
        "| §7 | 1↔1 integer hedge ratios | clean ratios like `A − 2·B` |\n",
        "| §8 | PCA factor decomposition | how many factors drive the group |\n",
        "| §9 | Composite index + per-product residual | which variant has the best idiosyncratic mean reversion |\n",
        "| §10 | 1↔many continuous basket K=1..4 | best real-weight basket per target |\n",
        "| §11 | 1↔many integer basket K=1..4 | clean integer baskets |\n",
        "| §12 | Pure integer linear combos k=2..5 | stationary baskets without a designated target |\n",
        "| §13 | Dashboard + residual plots | one-line winners + visual triage |\n",
        "\n",
        "All sections work on the same 5-product aligned panel, so this notebook should run end-to-end in seconds (not minutes).\n",
    ))

    # ---- §1 Setup ----
    cells.append(md("## §1 — Setup, config, helpers\n"))

    cells.append(code(
        "import math\n",
        "import time\n",
        "import warnings\n",
        "from pathlib import Path\n",
        "from itertools import combinations, product as iproduct\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import plotly.graph_objects as go\n",
        "import plotly.express as px\n",
        "from plotly.subplots import make_subplots\n",
        "from scipy.stats import kendalltau\n",
        "from sklearn.decomposition import PCA\n",
        "from statsmodels.tsa.stattools import adfuller, coint\n",
        "from IPython.display import display, Markdown\n",
        "\n",
        "%matplotlib inline\n",
        "warnings.filterwarnings(\"ignore\")\n",
        "sns.set_theme(style=\"whitegrid\", font_scale=0.9)\n",
        "pd.set_option(\"display.max_columns\", 80)\n",
        "pd.set_option(\"display.width\", 200)\n",
        "\n",
        "# ============ CONFIG ============\n",
        "DATA_DIR  = Path(\"ROUND_5\")\n",
        "ROUND     = 5\n",
        f"GROUP_KEY = \"{group_key}\"\n",
        f"GROUP_LABEL = \"{title}\"\n",
        f"OUT_DIR   = Path(\"{out_dir}\")\n",
        "OUT_DIR.mkdir(exist_ok=True)\n",
        "# ================================\n",
        "\n",
        f"PRODUCTS = {products_repr}\n",
        "POSITION_LIMIT = 10  # all Round-5 products\n",
        "\n",
        "# --- Combinatorial knobs (tiny within a 5-product group, so we can be exhaustive) ---\n",
        "K_MAX             = 4       # max basket size for §10/§11; 4 is exhaustive (target + 4 others = 5)\n",
        "INT_COEF_MIN      = -5\n",
        "INT_COEF_MAX      =  5\n",
        "TOP_PER_TARGET_K  = 50\n",
        "TOP_DISPLAY       = 40\n",
        "SUBSAMPLE_FOR_ADF = 20000   # random-ish row subsample for ADF (None = all)\n",
        "RANDOM_SEED       = 42\n",
        "WINDOW_FAST       = 200     # rolling window for residual plots\n",
        "WINDOW_ROLLING    = 5000    # rolling window for stability check\n",
        "MAX_LAG_LEAD      = 50      # ±lags for lead-lag cross-correlation\n",
        "\n",
        "print(f\"Group: {GROUP_LABEL}  ({len(PRODUCTS)} products)\")\n",
        "for p in PRODUCTS:\n",
        "    print(\"  -\", p)\n",
    ))

    # ---- helpers ----
    cells.append(code(
        "# ─── stat helpers ───\n",
        "def adf_p(series, subsample=None):\n",
        "    \"\"\"ADF p-value. Optionally subsample for speed.\"\"\"\n",
        "    if subsample is None:\n",
        "        subsample = SUBSAMPLE_FOR_ADF\n",
        "    s = pd.Series(series).dropna().values\n",
        "    if len(s) < 30 or np.std(s) == 0:\n",
        "        return np.nan\n",
        "    if subsample and len(s) > subsample:\n",
        "        idx = np.linspace(0, len(s) - 1, subsample).astype(int)\n",
        "        s = s[idx]\n",
        "    try:\n",
        "        return float(adfuller(s, autolag=\"AIC\")[1])\n",
        "    except Exception:\n",
        "        return np.nan\n",
        "\n",
        "\n",
        "def half_life(series):\n",
        "    \"\"\"OU half-life in ticks. NaN if non-reverting.\"\"\"\n",
        "    s = pd.Series(series).dropna().values\n",
        "    if len(s) < 50:\n",
        "        return np.nan\n",
        "    x_lag = s[:-1]\n",
        "    dx    = np.diff(s)\n",
        "    X     = np.column_stack([np.ones_like(x_lag), x_lag])\n",
        "    try:\n",
        "        b = np.linalg.lstsq(X, dx, rcond=None)[0][1]\n",
        "    except Exception:\n",
        "        return np.nan\n",
        "    return float(np.log(2) / -b) if (np.isfinite(b) and b < 0) else np.nan\n",
        "\n",
        "\n",
        "def fmt_basket(prods, coefs, max_terms=8):\n",
        "    \"\"\"Format a (signed) basket like '3*A − 2*B + C'.\"\"\"\n",
        "    parts = []\n",
        "    for p, c in zip(prods, coefs):\n",
        "        if abs(c) < 1e-9:\n",
        "            continue\n",
        "        sign = \"+\" if c > 0 else \"−\"\n",
        "        mag  = abs(c)\n",
        "        mag_s = f\"{int(round(mag))}\" if abs(mag - round(mag)) < 1e-6 else f\"{mag:.3f}\"\n",
        "        if mag_s == \"1\":\n",
        "            parts.append(f\"{sign} {p}\")\n",
        "        else:\n",
        "            parts.append(f\"{sign} {mag_s}*{p}\")\n",
        "    if not parts:\n",
        "        return \"(zero)\"\n",
        "    out = \" \".join(parts)\n",
        "    if out.startswith(\"+ \"):\n",
        "        out = out[2:]\n",
        "    return out[:200]\n",
    ))

    # ---- §2 Data load ----
    cells.append(md(
        "## §2 — Data load + aligned mid panel + raw viz\n",
        "\n",
        "Load every `prices_round_5_day_*.csv`, restrict to the 5 products of this group, build the global tick index `t = day · 1e6 + timestamp`, ffill empty-book mids, and pivot to a wide aligned panel. Then build the Gram matrix `G = Xcᵀ Xc / T` once (5×5, trivial) which underpins every downstream search.\n",
    ))

    cells.append(code(
        "import re\n",
        "\n",
        "def load_round5(data_dir: Path, products: list) -> pd.DataFrame:\n",
        "    files = sorted(data_dir.glob(\"prices_round_*_day_*.csv\"))\n",
        "    if not files:\n",
        "        raise FileNotFoundError(f\"No prices CSVs in {data_dir}\")\n",
        "    frames = []\n",
        "    for f in files:\n",
        "        df = pd.read_csv(f, sep=\";\")\n",
        "        if \"day\" not in df.columns:\n",
        "            m = re.search(r\"day_(-?\\d+)\", f.stem)\n",
        "            if m:\n",
        "                df[\"day\"] = int(m.group(1))\n",
        "        frames.append(df[df[\"product\"].isin(products)])\n",
        "    prices = pd.concat(frames, ignore_index=True)\n",
        "    prices[\"t\"] = prices[\"day\"].astype(int) * 1_000_000 + prices[\"timestamp\"].astype(int)\n",
        "    prices.loc[prices[\"mid_price\"] == 0, \"mid_price\"] = np.nan\n",
        "    prices[\"mid_price\"] = prices.groupby(\"product\")[\"mid_price\"].ffill()\n",
        "    return prices\n",
        "\n",
        "\n",
        "prices = load_round5(DATA_DIR, PRODUCTS)\n",
        "print(f\"Loaded {len(prices):,} rows across days {sorted(prices['day'].unique())}\")\n",
        "missing = [p for p in PRODUCTS if p not in set(prices['product'])]\n",
        "if missing:\n",
        "    print(f\"⚠ Missing from data: {missing}\")\n",
        "\n",
        "mid = prices.pivot_table(index=\"t\", columns=\"product\", values=\"mid_price\", aggfunc=\"last\")\n",
        "present = [p for p in PRODUCTS if p in mid.columns]\n",
        "mid = mid[present].sort_index()\n",
        "mid_aligned = mid.dropna()\n",
        "T, P = mid_aligned.shape\n",
        "print(f\"\\nAligned panel: T = {T:,} ticks × P = {P} products\")\n",
        "\n",
        "# Numpy backing arrays + Gram matrix\n",
        "X       = mid_aligned.values.astype(np.float64)\n",
        "columns = list(mid_aligned.columns)\n",
        "mean_X  = X.mean(axis=0)\n",
        "Xc      = X - mean_X\n",
        "G       = (Xc.T @ Xc) / T\n",
        "var     = np.diag(G).copy()\n",
        "std     = np.sqrt(var)\n",
        "rets    = mid_aligned.diff().iloc[1:]\n",
        "\n",
        "summary = pd.DataFrame({\n",
        "    \"mean\":    mid_aligned.mean(),\n",
        "    \"std\":     std,\n",
        "    \"min\":     mid_aligned.min(),\n",
        "    \"max\":     mid_aligned.max(),\n",
        "    \"ret_std\": rets.std(),\n",
        "})\n",
        "print(\"\\n=== Per-product summary ===\")\n",
        "display(summary.round(3))\n",
    ))

    # raw viz
    cells.append(code(
        "# Raw mid-price plot — separate panels because absolute scales may differ\n",
        "fig = make_subplots(rows=len(columns), cols=1, shared_xaxes=True,\n",
        "                    vertical_spacing=0.02,\n",
        "                    subplot_titles=columns)\n",
        "for i, p in enumerate(columns):\n",
        "    fig.add_trace(go.Scatter(y=mid_aligned[p].values, name=p, line=dict(width=0.7)),\n",
        "                  row=i+1, col=1)\n",
        "fig.update_layout(height=180 * len(columns), title=f\"{GROUP_LABEL}: raw mid prices\",\n",
        "                  showlegend=False, hovermode=\"x unified\")\n",
        "fig.show()\n",
        "\n",
        "# Z-scored overlay so co-movement is visually obvious\n",
        "z = (mid_aligned - mid_aligned.mean()) / mid_aligned.std()\n",
        "fig2 = go.Figure()\n",
        "for p in columns:\n",
        "    fig2.add_trace(go.Scatter(y=z[p].values, name=p, line=dict(width=0.8)))\n",
        "fig2.update_layout(height=420, title=f\"{GROUP_LABEL}: z-scored mids overlay\",\n",
        "                   hovermode=\"x unified\")\n",
        "fig2.show()\n",
    ))

    # ---- §3 correlations ----
    cells.append(md(
        "## §3 — Pearson + Spearman + Kendall correlations\n",
        "\n",
        "Three rankings of the same C(5,2) = 10 pairs:\n",
        "\n",
        "1. **Pearson (level)** — raw mid co-movement. High here alone is suspect (shared drift).\n",
        "2. **Pearson (returns / first-difference)** — tick-by-tick co-movement. The honest signal.\n",
        "3. **Spearman / Kendall (returns)** — rank-based, robust to outliers. Should agree with Pearson(returns) for tightly-traded products; large divergence flags a non-linear relationship or a few influential ticks.\n",
        "\n",
        "We then compute a joint score `√(|pearson_level| · |pearson_ret|)` to surface pairs where **both** are high — the strongest pair-trade candidates.\n",
    ))

    cells.append(code(
        "corr_level    = mid_aligned.corr(method=\"pearson\")\n",
        "corr_ret      = rets.corr(method=\"pearson\")\n",
        "corr_spearman = rets.corr(method=\"spearman\")\n",
        "\n",
        "# Kendall is O(n²) per pair so subsample for speed\n",
        "kend_subsample = min(len(rets), 5000)\n",
        "rets_kend = rets.sample(n=kend_subsample, random_state=RANDOM_SEED).sort_index() if len(rets) > kend_subsample else rets\n",
        "corr_kendall = rets_kend.corr(method=\"kendall\")\n",
        "\n",
        "\n",
        "def pair_long(C: pd.DataFrame, val_name: str) -> pd.DataFrame:\n",
        "    rows = []\n",
        "    cols = list(C.columns)\n",
        "    for i, a in enumerate(cols):\n",
        "        for j, b in enumerate(cols):\n",
        "            if i >= j:\n",
        "                continue\n",
        "            rows.append({\"a\": a, \"b\": b, val_name: C.iat[i, j]})\n",
        "    return pd.DataFrame(rows)\n",
        "\n",
        "\n",
        "p_level = pair_long(corr_level,    \"pearson_level\")\n",
        "p_ret   = pair_long(corr_ret,      \"pearson_ret\")\n",
        "p_spear = pair_long(corr_spearman, \"spearman_ret\")\n",
        "p_kend  = pair_long(corr_kendall,  \"kendall_ret\")\n",
        "\n",
        "both = p_level.merge(p_ret, on=[\"a\", \"b\"]) \\\n",
        "              .merge(p_spear, on=[\"a\", \"b\"]) \\\n",
        "              .merge(p_kend,  on=[\"a\", \"b\"])\n",
        "both[\"abs_level\"]   = both[\"pearson_level\"].abs()\n",
        "both[\"abs_ret\"]     = both[\"pearson_ret\"].abs()\n",
        "both[\"joint_score\"] = np.sqrt(both[\"abs_level\"] * both[\"abs_ret\"])\n",
        "both[\"par_minus_spear\"] = (both[\"pearson_ret\"] - both[\"spearman_ret\"]).abs()  # non-linearity flag\n",
        "\n",
        "both.to_csv(OUT_DIR / \"pair_correlations.csv\", index=False)\n",
        "\n",
        "print(\"=== All 10 pairs sorted by joint score ===\")\n",
        "display(both.sort_values(\"joint_score\", ascending=False).round(4))\n",
        "\n",
        "print(\"\\n=== Pairs where Pearson(ret) and Spearman(ret) DISAGREE most ===\")\n",
        "display(both.sort_values(\"par_minus_spear\", ascending=False).head(5).round(4))\n",
        "\n",
        "# Heatmaps\n",
        "fig, axs = plt.subplots(2, 2, figsize=(13, 10))\n",
        "for ax, C, title in [\n",
        "    (axs[0, 0], corr_level,    \"Pearson — level\"),\n",
        "    (axs[0, 1], corr_ret,      \"Pearson — returns\"),\n",
        "    (axs[1, 0], corr_spearman, \"Spearman — returns\"),\n",
        "    (axs[1, 1], corr_kendall,  f\"Kendall — returns (n={kend_subsample})\"),\n",
        "]:\n",
        "    sns.heatmap(C, cmap=\"coolwarm\", center=0, vmin=-1, vmax=1, square=True,\n",
        "                annot=True, fmt=\".3f\", cbar_kws={\"shrink\": 0.7}, ax=ax)\n",
        "    ax.set_title(title)\n",
        "    ax.tick_params(axis=\"x\", labelsize=7, rotation=45)\n",
        "    ax.tick_params(axis=\"y\", labelsize=7)\n",
        "plt.tight_layout(); plt.show()\n",
    ))

    # scatter matrix
    cells.append(code(
        "# Pairwise scatter matrix on returns — visual sanity check for non-linear / heavy-tailed structure\n",
        "sample_n = min(len(rets), 3000)\n",
        "rets_s = rets.sample(n=sample_n, random_state=RANDOM_SEED) if len(rets) > sample_n else rets\n",
        "sns.set(style=\"white\")\n",
        "g = sns.pairplot(rets_s, plot_kws=dict(s=4, alpha=0.3), diag_kind=\"kde\", height=1.7)\n",
        "g.fig.suptitle(f\"{GROUP_LABEL}: pairwise return scatter (n={sample_n})\", y=1.02, fontsize=11)\n",
        "plt.show()\n",
        "sns.set_theme(style=\"whitegrid\", font_scale=0.9)\n",
    ))

    # ---- §4 rolling correlation ----
    cells.append(md(
        "## §4 — Rolling correlation stability\n",
        "\n",
        "Single-number Pearson averages a relationship over the whole panel. A pair can have decent overall correlation while flipping sign within the window — useless for trading.\n",
        "\n",
        "We compute rolling Pearson(returns) over a window of `WINDOW_ROLLING` ticks for every pair and look at:\n",
        "\n",
        "- The **time-series** of rolling correlation (eyeball stability + regime changes)\n",
        "- The **range** [min, max] across the window — pairs with a tight range are reliable\n",
        "- The **fraction of windows above 0.5** (or below −0.5) — a robust ‘consistency’ score\n",
    ))

    cells.append(code(
        "win = min(WINDOW_ROLLING, max(500, T // 20))\n",
        "rolling_rows = []\n",
        "rolling_series = {}\n",
        "for a, b in combinations(columns, 2):\n",
        "    rc = rets[a].rolling(win).corr(rets[b]).dropna()\n",
        "    if len(rc) == 0:\n",
        "        continue\n",
        "    rolling_series[f\"{a}|{b}\"] = rc\n",
        "    rolling_rows.append({\n",
        "        \"a\": a, \"b\": b,\n",
        "        \"mean\":   float(rc.mean()),\n",
        "        \"std\":    float(rc.std()),\n",
        "        \"min\":    float(rc.min()),\n",
        "        \"max\":    float(rc.max()),\n",
        "        \"frac_above_0.5\": float((rc.abs() > 0.5).mean()),\n",
        "        \"frac_above_0.3\": float((rc.abs() > 0.3).mean()),\n",
        "    })\n",
        "rolling_summary = pd.DataFrame(rolling_rows).sort_values(\"frac_above_0.5\", ascending=False)\n",
        "rolling_summary.to_csv(OUT_DIR / \"rolling_correlation_summary.csv\", index=False)\n",
        "\n",
        "print(f\"Rolling Pearson(returns) summary, window={win} ticks:\")\n",
        "display(rolling_summary.round(3))\n",
        "\n",
        "# Plot all 10 rolling correlations\n",
        "fig = go.Figure()\n",
        "for k, rc in rolling_series.items():\n",
        "    fig.add_trace(go.Scatter(y=rc.values, name=k, line=dict(width=0.8)))\n",
        "fig.add_hline(y=0, line_dash=\"dot\", line_color=\"black\")\n",
        "fig.update_layout(height=480, title=f\"{GROUP_LABEL}: rolling Pearson(returns), window={win}\",\n",
        "                  hovermode=\"x unified\")\n",
        "fig.show()\n",
    ))

    # ---- §5 lead-lag ----
    cells.append(md(
        "## §5 — Lead-lag cross-correlation\n",
        "\n",
        "For each ordered pair `(a, b)`, compute `corr(rets[a], rets[b].shift(L))` for L ∈ {−MAX_LAG_LEAD … MAX_LAG_LEAD}. The lag with peak |correlation| says which product **leads** the other (positive L: `a` leads `b`).\n",
        "\n",
        "Within a tight group, ‘leadership’ is usually informational — one variant is the price-discovery instrument and the rest follow. That's a tradeable structural feature: if A leads B and the contemporaneous spread blows out, the next-tick movement in B may be predictable.\n",
    ))

    cells.append(code(
        "lags = list(range(-MAX_LAG_LEAD, MAX_LAG_LEAD + 1))\n",
        "leadlag_curves = {}\n",
        "leadlag_rows = []\n",
        "for a, b in combinations(columns, 2):\n",
        "    ra = rets[a]\n",
        "    rb = rets[b]\n",
        "    cs = []\n",
        "    for L in lags:\n",
        "        if L >= 0:\n",
        "            c = ra.iloc[L:].reset_index(drop=True).corr(rb.iloc[:len(rb) - L].reset_index(drop=True))\n",
        "        else:\n",
        "            c = ra.iloc[:len(ra) + L].reset_index(drop=True).corr(rb.iloc[-L:].reset_index(drop=True))\n",
        "        cs.append(c)\n",
        "    cs = np.asarray(cs)\n",
        "    leadlag_curves[f\"{a}|{b}\"] = cs\n",
        "    best_idx = int(np.nanargmax(np.abs(cs)))\n",
        "    best_lag = lags[best_idx]\n",
        "    leadlag_rows.append({\n",
        "        \"a\": a, \"b\": b,\n",
        "        \"corr_at_0\":   float(cs[lags.index(0)]),\n",
        "        \"peak_corr\":   float(cs[best_idx]),\n",
        "        \"peak_abs\":    float(abs(cs[best_idx])),\n",
        "        \"peak_lag\":    int(best_lag),\n",
        "        \"interpretation\": (\n",
        "            \"contemporaneous\" if best_lag == 0\n",
        "            else (f\"{a} leads {b} by {best_lag}\" if best_lag > 0 else f\"{b} leads {a} by {-best_lag}\")\n",
        "        ),\n",
        "    })\n",
        "leadlag_summary = pd.DataFrame(leadlag_rows).sort_values(\"peak_abs\", ascending=False)\n",
        "leadlag_summary.to_csv(OUT_DIR / \"leadlag_summary.csv\", index=False)\n",
        "\n",
        "print(\"=== Lead-lag summary (returns), peak |corr| within ±%d ticks ===\" % MAX_LAG_LEAD)\n",
        "display(leadlag_summary.round(4))\n",
        "\n",
        "# Plot the curves\n",
        "fig = go.Figure()\n",
        "for k, cs in leadlag_curves.items():\n",
        "    fig.add_trace(go.Scatter(x=lags, y=cs, name=k, mode=\"lines\"))\n",
        "fig.add_vline(x=0, line_dash=\"dot\", line_color=\"black\")\n",
        "fig.update_layout(height=440,\n",
        "                  title=f\"{GROUP_LABEL}: lead-lag cross-correlation of returns (positive lag: a leads b)\",\n",
        "                  xaxis_title=\"lag L (ticks)\", yaxis_title=\"corr(rets[a], rets[b].shift(L))\",\n",
        "                  hovermode=\"x unified\")\n",
        "fig.show()\n",
    ))

    # ---- §6 cointegration ----
    cells.append(md(
        "## §6 — Pairwise cointegration (all 10 pairs)\n",
        "\n",
        "For every pair `(a, b)`:\n",
        "\n",
        "1. OLS hedge ratio `h = cov(a, b) / var(b)` (closed form via Gram matrix).\n",
        "2. Spread `s = a − h·b`, residual std ratio = `√(1 − corr²)`.\n",
        "3. **Engle-Granger** cointegration p-value (`coint`) — uses the right critical values for an OLS-fitted spread.\n",
        "4. ADF p-value on the spread.\n",
        "5. OU half-life of the spread.\n",
        "\n",
        "Within 5 products this is 10 pairs — we run the full test on every one, no two-stage shortlist.\n",
    ))

    cells.append(code(
        "COINT_MAXLAG = 5\n",
        "\n",
        "def coint_p_fast(xi, xj):\n",
        "    try:\n",
        "        return float(coint(xi, xj, trend=\"c\", maxlag=COINT_MAXLAG, autolag=None)[1])\n",
        "    except Exception:\n",
        "        return np.nan\n",
        "\n",
        "\n",
        "def adf_p_fast(spread):\n",
        "    s = pd.Series(spread).dropna().values\n",
        "    if SUBSAMPLE_FOR_ADF and len(s) > SUBSAMPLE_FOR_ADF:\n",
        "        s = s[np.linspace(0, len(s) - 1, SUBSAMPLE_FOR_ADF).astype(int)]\n",
        "    if len(s) < 30 or np.std(s) == 0:\n",
        "        return np.nan\n",
        "    try:\n",
        "        return float(adfuller(s, maxlag=COINT_MAXLAG, autolag=None)[1])\n",
        "    except Exception:\n",
        "        return np.nan\n",
        "\n",
        "\n",
        "rows = []\n",
        "for i, j in combinations(range(P), 2):\n",
        "    if var[j] == 0 or var[i] == 0:\n",
        "        continue\n",
        "    h        = G[i, j] / var[j]\n",
        "    rvar     = var[i] - h * G[i, j]\n",
        "    lvl_corr = G[i, j] / np.sqrt(var[i] * var[j])\n",
        "    spread   = X[:, i] - h * X[:, j]\n",
        "    rows.append({\n",
        "        \"a\": columns[i], \"b\": columns[j],\n",
        "        \"hedge_ratio\":     float(h),\n",
        "        \"level_corr\":      float(lvl_corr),\n",
        "        \"resid_std_ratio\": float(np.sqrt(max(rvar, 0) / var[i])),\n",
        "        \"eg_p\":            coint_p_fast(X[:, i], X[:, j]),\n",
        "        \"adf_p\":           adf_p_fast(spread),\n",
        "        \"half_life\":       half_life(spread),\n",
        "    })\n",
        "pair_table = pd.DataFrame(rows).sort_values(\"eg_p\").reset_index(drop=True)\n",
        "pair_table.to_csv(OUT_DIR / \"pair_cointegration.csv\", index=False)\n",
        "\n",
        "print(\"=== All pairs by EG p-value ===\")\n",
        "display(pair_table.round(4))\n",
    ))

    # ---- §7 integer hedge ----
    cells.append(md(
        "## §7 — Pairwise integer hedge ratios\n",
        "\n",
        "Real-valued hedge ratios are messy in practice (you can't trade 1.7 units). Search the integer grid `[INT_COEF_MIN..INT_COEF_MAX] \\ {0}` per pair and pick the integer that minimises spread variance:\n",
        "\n",
        "`var(a − k·b) = var(a) − 2·k·cov(a,b) + k²·var(b)`\n",
        "\n",
        "(closed form via Gram matrix). Then run ADF + half-life on the integer spread.\n",
        "\n",
        "**Position-limit reminder**: limit is **10**, so a pair `a − k·b` traded at one unit means `±10 a, ∓10·k b` at full size. Prefer `|k| ≤ 3`.\n",
    ))

    cells.append(code(
        "int_grid = [k for k in range(INT_COEF_MIN, INT_COEF_MAX + 1) if k != 0]\n",
        "int_rows = []\n",
        "for _, r in pair_table.iterrows():\n",
        "    a, b = r[\"a\"], r[\"b\"]\n",
        "    i, j = columns.index(a), columns.index(b)\n",
        "    best_k, best_v = None, np.inf\n",
        "    for k in int_grid:\n",
        "        v = var[i] - 2 * k * G[i, j] + k ** 2 * var[j]\n",
        "        if v < best_v:\n",
        "            best_v, best_k = v, k\n",
        "    spread = X[:, i] - best_k * X[:, j]\n",
        "    int_rows.append({\n",
        "        \"a\": a, \"b\": b,\n",
        "        \"ols_h\":               r[\"hedge_ratio\"],\n",
        "        \"int_h\":               int(best_k),\n",
        "        \"ols_resid_std_ratio\": r[\"resid_std_ratio\"],\n",
        "        \"int_resid_std_ratio\": float(np.sqrt(max(best_v, 0) / var[i])),\n",
        "        \"int_resid_inflation\": float(np.sqrt(max(best_v, 0) / var[i]) / max(r[\"resid_std_ratio\"], 1e-9)),\n",
        "        \"int_adf_p\":           adf_p(spread),\n",
        "        \"int_half_life\":       half_life(spread),\n",
        "    })\n",
        "int_pair_table = pd.DataFrame(int_rows).sort_values(\"int_adf_p\").reset_index(drop=True)\n",
        "int_pair_table.to_csv(OUT_DIR / \"pair_integer_hedge.csv\", index=False)\n",
        "\n",
        "print(\"=== Integer-hedge pairs by ADF p ===\")\n",
        "display(int_pair_table.round(4))\n",
        "\n",
        "print(\"\\n=== Pairs where rounding is nearly free (inflation < 1.05) ===\")\n",
        "display(int_pair_table.query(\"int_resid_inflation < 1.05\").sort_values(\"int_adf_p\").round(4))\n",
    ))

    # ---- §8 PCA ----
    cells.append(md(
        "## §8 — PCA factor decomposition\n",
        "\n",
        "Run PCA on the **return panel** (centered, *not* scaled — same units, similar volatility). For 5 highly correlated products we expect:\n",
        "\n",
        "- **PC1** carries the dominant common factor (group-wide drift). Loading sign and magnitude tells us which variant moves with the group most.\n",
        "- **PC2..PC5** are the idiosyncratic axes. Each PC's residuals are an orthogonal candidate spread; if `PC2` (say) is mean-reverting, we have a tradeable basket whose weights are the PC2 loadings.\n",
        "\n",
        "We test every PC residual for ADF / half-life. PC1 should *not* be mean-reverting (it's the trend). PC2..PC5 might.\n",
    ))

    cells.append(code(
        "pca = PCA(n_components=P)\n",
        "ret_arr = rets.values\n",
        "ret_centered = ret_arr - ret_arr.mean(axis=0)\n",
        "scores = pca.fit_transform(ret_centered)  # (T-1, P)\n",
        "loadings = pca.components_  # (P, P) — rows are PCs, columns are products\n",
        "\n",
        "explained = pd.DataFrame({\n",
        "    \"pc\": [f\"PC{i+1}\" for i in range(P)],\n",
        "    \"explained_var_ratio\": pca.explained_variance_ratio_,\n",
        "    \"cumulative\": np.cumsum(pca.explained_variance_ratio_),\n",
        "})\n",
        "print(\"=== Variance explained per PC ===\")\n",
        "display(explained.round(4))\n",
        "\n",
        "load_df = pd.DataFrame(loadings,\n",
        "                       index=[f\"PC{i+1}\" for i in range(P)],\n",
        "                       columns=columns)\n",
        "print(\"\\n=== Loadings (rows: PCs, cols: products) ===\")\n",
        "display(load_df.round(3))\n",
        "\n",
        "# Reconstruct PC residuals at the LEVEL (cumulative sum of returns gives a level-like series)\n",
        "pc_levels = pd.DataFrame(np.cumsum(scores, axis=0),\n",
        "                         columns=[f\"PC{i+1}\" for i in range(P)])\n",
        "\n",
        "pc_rows = []\n",
        "for i in range(P):\n",
        "    name   = f\"PC{i+1}\"\n",
        "    score  = scores[:, i]\n",
        "    level  = pc_levels[name].values\n",
        "    pc_rows.append({\n",
        "        \"pc\":                  name,\n",
        "        \"explained_var_ratio\": float(pca.explained_variance_ratio_[i]),\n",
        "        \"loadings\":            load_df.loc[name].round(3).to_dict(),\n",
        "        \"adf_p_score\":         adf_p(score),         # returns-space (should be small for stationary noise)\n",
        "        \"adf_p_level\":         adf_p(level),         # cumulative — small means stationary, NOT random walk\n",
        "        \"half_life_level\":     half_life(level),\n",
        "    })\n",
        "pc_table = pd.DataFrame(pc_rows)\n",
        "pc_table.to_csv(OUT_DIR / \"pca_residuals.csv\", index=False)\n",
        "print(\"\\n=== PC residual stationarity ===\")\n",
        "display(pc_table)\n",
        "\n",
        "# Plot the level-space PC trajectories\n",
        "fig = make_subplots(rows=P, cols=1, shared_xaxes=True, vertical_spacing=0.03,\n",
        "                    subplot_titles=[f\"PC{i+1}  (var={pca.explained_variance_ratio_[i]:.2%})\"\n",
        "                                    for i in range(P)])\n",
        "for i in range(P):\n",
        "    fig.add_trace(go.Scatter(y=pc_levels.iloc[:, i].values, line=dict(width=0.8),\n",
        "                             name=f\"PC{i+1}\"), row=i+1, col=1)\n",
        "fig.update_layout(height=180 * P, showlegend=False, hovermode=\"x unified\",\n",
        "                  title=f\"{GROUP_LABEL}: PC level trajectories (cumulative scores)\")\n",
        "fig.show()\n",
        "\n",
        "# Loadings heatmap\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "sns.heatmap(load_df, annot=True, fmt=\".2f\", cmap=\"coolwarm\", center=0,\n",
        "            cbar_kws={\"label\": \"loading\"}, ax=ax)\n",
        "ax.set_title(f\"{GROUP_LABEL}: PCA loadings\")\n",
        "plt.tight_layout(); plt.show()\n",
    ))

    # ---- §9 composite + residuals ----
    cells.append(md(
        "## §9 — Composite index + per-product idiosyncratic residual\n",
        "\n",
        "Build the group composite index as the **z-mean** of the 5 mids (same definition as §7 of the master notebook). For each product `p`, the residual `p − OLS(p ~ index)` is its idiosyncratic component. If that residual is mean-reverting, you can trade `p` against the index — and the basket is **automatically integer-friendly** because the index weight is uniform across the other 4 products.\n",
        "\n",
        "We also report the OLS β of each product on the index: a high β means the product is the most responsive to the common factor, which is sometimes the cleanest pair-trade leg.\n",
    ))

    cells.append(code(
        "z = (mid_aligned - mid_aligned.mean()) / mid_aligned.std(ddof=0).replace(0, np.nan)\n",
        "z = z.dropna(axis=1)\n",
        "index_series = z.mean(axis=1)\n",
        "index_series.name = \"GROUP_INDEX\"\n",
        "index_series.to_csv(OUT_DIR / \"group_index.csv\")\n",
        "\n",
        "idx_rows = []\n",
        "for p in columns:\n",
        "    s = mid_aligned[p]\n",
        "    # OLS p ~ a + b·index\n",
        "    A = np.column_stack([np.ones_like(index_series.values), index_series.values])\n",
        "    coef, *_ = np.linalg.lstsq(A, s.values, rcond=None)\n",
        "    a_int, b_idx = coef\n",
        "    fitted = A @ coef\n",
        "    resid  = s.values - fitted\n",
        "    idx_rows.append({\n",
        "        \"product\":         p,\n",
        "        \"intercept\":       float(a_int),\n",
        "        \"beta_to_index\":   float(b_idx),\n",
        "        \"resid_std\":       float(np.std(resid)),\n",
        "        \"r_squared\":       float(1 - np.var(resid) / np.var(s.values)),\n",
        "        \"adf_p\":           adf_p(resid),\n",
        "        \"half_life\":       half_life(resid),\n",
        "    })\n",
        "idx_table = pd.DataFrame(idx_rows).sort_values(\"adf_p\")\n",
        "idx_table.to_csv(OUT_DIR / \"product_vs_index.csv\", index=False)\n",
        "print(\"=== Each product regressed on the group composite index ===\")\n",
        "display(idx_table.round(4))\n",
        "\n",
        "# Residual plots\n",
        "fig = make_subplots(rows=P, cols=1, shared_xaxes=True, vertical_spacing=0.03,\n",
        "                    subplot_titles=[f\"{p} − OLS·index   (β={r['beta_to_index']:.3f}, ADF p={r['adf_p']:.3g})\"\n",
        "                                    for p, r in zip(columns, [idx_table[idx_table['product']==p].iloc[0] for p in columns])])\n",
        "for i, p in enumerate(columns):\n",
        "    s = mid_aligned[p]\n",
        "    A = np.column_stack([np.ones_like(index_series.values), index_series.values])\n",
        "    coef, *_ = np.linalg.lstsq(A, s.values, rcond=None)\n",
        "    resid = s.values - A @ coef\n",
        "    fig.add_trace(go.Scatter(y=resid, line=dict(width=0.7), name=p), row=i+1, col=1)\n",
        "    fig.add_hline(y=0, line_dash=\"dot\", line_color=\"black\", row=i+1, col=1)\n",
        "fig.update_layout(height=180 * P, showlegend=False, hovermode=\"x unified\",\n",
        "                  title=f\"{GROUP_LABEL}: idiosyncratic residual = product − OLS(product ~ index)\")\n",
        "fig.show()\n",
    ))

    # ---- §10 continuous basket ----
    cells.append(md(
        "## §10 — 1↔many continuous basket search (K = 1..4)\n",
        "\n",
        "For each product as **target**, exhaustively try every subset of size `k = 1..4` from the other 4 products as a hedge basket. Within a 5-product group this is tiny:\n",
        "\n",
        "- K=1: 5 × 4 = 20 fits\n",
        "- K=2: 5 × C(4,2) = 30 fits\n",
        "- K=3: 5 × C(4,3) = 20 fits\n",
        "- K=4: 5 × C(4,4) = 5 fits\n",
        "\n",
        "Total = 75 fits. Every one runs ADF + half-life (no shortlist needed). The Gram trick keeps each fit O(k³).\n",
    ))

    cells.append(code(
        "def basket_resid_var(target_idx, S):\n",
        "    Gss = G[np.ix_(S, S)]\n",
        "    Gst = G[S, target_idx]\n",
        "    try:\n",
        "        beta = np.linalg.solve(Gss, Gst)\n",
        "    except np.linalg.LinAlgError:\n",
        "        return np.inf, None\n",
        "    rvar = var[target_idx] - beta @ Gst\n",
        "    if rvar < -1e-9:\n",
        "        return np.inf, None\n",
        "    return max(rvar, 0.0), beta\n",
        "\n",
        "\n",
        "def reconstruct_residual(target_idx, S, beta):\n",
        "    return Xc[:, target_idx] - Xc[:, S] @ beta\n",
        "\n",
        "\n",
        "basket_results = {}\n",
        "for k in range(1, K_MAX + 1):\n",
        "    rows = []\n",
        "    for ti in range(P):\n",
        "        cands = [j for j in range(P) if j != ti]\n",
        "        for combo in combinations(cands, k):\n",
        "            S = list(combo)\n",
        "            rvar, beta = basket_resid_var(ti, S)\n",
        "            if not np.isfinite(rvar) or beta is None:\n",
        "                continue\n",
        "            target = columns[ti]\n",
        "            basket = [columns[s] for s in S]\n",
        "            resid  = reconstruct_residual(ti, S, beta)\n",
        "            rows.append({\n",
        "                \"target\":     target,\n",
        "                \"k\":          k,\n",
        "                \"basket\":     basket,\n",
        "                \"ols_beta\":   beta.tolist(),\n",
        "                \"resid_var\":  float(rvar),\n",
        "                \"r_squared\":  float(1 - rvar / var[ti]) if var[ti] > 0 else np.nan,\n",
        "                \"adf_p\":      adf_p(resid),\n",
        "                \"half_life\":  half_life(resid),\n",
        "                \"S_idx\":      S,\n",
        "                \"target_idx\": ti,\n",
        "            })\n",
        "    df = pd.DataFrame(rows).sort_values(\"adf_p\").reset_index(drop=True)\n",
        "    df[\"basket_str\"] = df.apply(\n",
        "        lambda r: fmt_basket([r[\"target\"]] + r[\"basket\"], [1.0] + list(-np.array(r[\"ols_beta\"]))),\n",
        "        axis=1)\n",
        "    basket_results[k] = df\n",
        "    df.to_csv(OUT_DIR / f\"basket_continuous_K{k}.csv\", index=False)\n",
        "    print(f\"\\n=== Top continuous baskets — K = {k} (sorted by ADF p) ===\")\n",
        "    display(df.head(TOP_DISPLAY)[\n",
        "        [\"target\", \"k\", \"basket_str\", \"r_squared\", \"adf_p\", \"half_life\"]\n",
        "    ].round(4))\n",
    ))

    # ---- §11 integer basket ----
    cells.append(md(
        "## §11 — 1↔many integer-coefficient basket search\n",
        "\n",
        "For every continuous basket above, find the closest integer vector that still minimises residual variance:\n",
        "\n",
        "1. Round OLS β to nearest integer in `[INT_COEF_MIN, INT_COEF_MAX]`.\n",
        "2. Search the 3ᵏ neighbourhood around the rounded vector.\n",
        "3. For tiny baskets (k ≤ 2) also try the **full** integer grid.\n",
        "4. Pick the integer vector minimising `cᵀ G[S,S] c − 2 cᵀ G[S,t] + G[t,t]`.\n",
        "\n",
        "Then run ADF + half-life on the integer spread and report the **inflation ratio** `int_resid_std / ols_resid_std`. Inflation < 1.05 means rounding cost is essentially free.\n",
    ))

    cells.append(code(
        "def integer_var(c_int, target_idx, S):\n",
        "    c = np.asarray(c_int, dtype=float)\n",
        "    return var[target_idx] - 2 * c @ G[S, target_idx] + c @ G[np.ix_(S, S)] @ c\n",
        "\n",
        "\n",
        "def integer_search_local(beta, target_idx, S, radius=1):\n",
        "    near = np.clip(np.round(beta).astype(int), INT_COEF_MIN, INT_COEF_MAX)\n",
        "    best_c, best_v = None, np.inf\n",
        "    deltas = list(range(-radius, radius + 1))\n",
        "    for d in iproduct(deltas, repeat=len(beta)):\n",
        "        c = np.clip(near + np.array(d), INT_COEF_MIN, INT_COEF_MAX)\n",
        "        if (c == 0).all():\n",
        "            continue\n",
        "        v = integer_var(c, target_idx, S)\n",
        "        if v < best_v:\n",
        "            best_v, best_c = v, c.copy()\n",
        "    return best_c, best_v\n",
        "\n",
        "\n",
        "def integer_search_full(target_idx, S):\n",
        "    best_c, best_v = None, np.inf\n",
        "    rng = list(range(INT_COEF_MIN, INT_COEF_MAX + 1))\n",
        "    for c in iproduct(rng, repeat=len(S)):\n",
        "        c_arr = np.asarray(c, dtype=int)\n",
        "        if (c_arr == 0).all():\n",
        "            continue\n",
        "        v = integer_var(c_arr, target_idx, S)\n",
        "        if v < best_v:\n",
        "            best_v, best_c = v, c_arr.copy()\n",
        "    return best_c, best_v\n",
        "\n",
        "\n",
        "def integer_baskets_per_K(df_top_continuous, full_grid_k_max=3):\n",
        "    rows = []\n",
        "    for _, row in df_top_continuous.iterrows():\n",
        "        ti    = row[\"target_idx\"]\n",
        "        S     = row[\"S_idx\"]\n",
        "        beta  = np.asarray(row[\"ols_beta\"])\n",
        "        if len(S) <= full_grid_k_max:\n",
        "            c_full, v_full = integer_search_full(ti, S)\n",
        "        else:\n",
        "            c_full, v_full = None, np.inf\n",
        "        c_local, v_local   = integer_search_local(beta, ti, S, radius=1)\n",
        "        if c_full is not None and v_full < v_local:\n",
        "            c_int, v_int = c_full, v_full\n",
        "        else:\n",
        "            c_int, v_int = c_local, v_local\n",
        "        if c_int is None:\n",
        "            continue\n",
        "        target = columns[ti]\n",
        "        basket = [columns[s] for s in S]\n",
        "        spread = X[:, ti] - X[:, S] @ c_int.astype(float)\n",
        "        rows.append({\n",
        "            \"target\":              target,\n",
        "            \"k\":                   len(S),\n",
        "            \"basket\":              basket,\n",
        "            \"ols_beta\":            beta.tolist(),\n",
        "            \"int_coefs\":           [int(c) for c in c_int],\n",
        "            \"int_basket_str\":      fmt_basket([target] + basket, [1.0] + list(-c_int.astype(float))),\n",
        "            \"ols_resid_std_ratio\": float(np.sqrt(max(row[\"resid_var\"], 0) / var[ti])),\n",
        "            \"int_resid_std_ratio\": float(np.sqrt(max(v_int, 0) / var[ti])),\n",
        "            \"int_resid_inflation\": float(np.sqrt(max(v_int, 0) / max(row[\"resid_var\"], 1e-12))),\n",
        "            \"max_abs_coef\":        int(max(abs(c) for c in c_int)),\n",
        "            \"int_adf_p\":           adf_p(spread),\n",
        "            \"int_half_life\":       half_life(spread),\n",
        "        })\n",
        "    return pd.DataFrame(rows).sort_values(\"int_adf_p\").reset_index(drop=True)\n",
        "\n",
        "\n",
        "basket_int = {}\n",
        "for k, df_cont in basket_results.items():\n",
        "    df_int = integer_baskets_per_K(df_cont)\n",
        "    basket_int[k] = df_int\n",
        "    df_int.to_csv(OUT_DIR / f\"basket_integer_K{k}.csv\", index=False)\n",
        "    print(f\"\\n=== Top integer baskets — K = {k} (sorted by ADF p) ===\")\n",
        "    display(df_int.head(TOP_DISPLAY)[\n",
        "        [\"target\", \"k\", \"int_basket_str\", \"max_abs_coef\",\n",
        "         \"int_resid_std_ratio\", \"int_resid_inflation\", \"int_adf_p\", \"int_half_life\"]\n",
        "    ].round(4))\n",
        "\n",
        "    cheap = df_int.query(\"int_resid_inflation < 1.05 and max_abs_coef <= 3\")\n",
        "    if len(cheap):\n",
        "        print(f\"\\n  → Cheap integer baskets (inflation < 1.05, max|c| ≤ 3) for K = {k}:\")\n",
        "        display(cheap.head(TOP_DISPLAY)[\n",
        "            [\"target\", \"int_basket_str\", \"max_abs_coef\",\n",
        "             \"int_resid_std_ratio\", \"int_adf_p\", \"int_half_life\"]\n",
        "        ].round(4))\n",
    ))

    # ---- §12 pure integer combos ----
    cells.append(md(
        "## §12 — Pure integer linear combinations (no target, no hedge)\n",
        "\n",
        "Find baskets `c₁·P₁ + c₂·P₂ + … + cₖ·Pₖ` (k ∈ {2,3,4,5}) that mean-revert without designating any product as ‘target’. This is the arb-trader's lens — *any* cheap integer combination of the order book that reverts.\n",
        "\n",
        "Algorithm per subset `S`:\n",
        "\n",
        "1. Smallest-eigenvalue eigenvector of `G[S,S]` → unit-norm direction of least variance.\n",
        "2. Scale so `max |vᵢ| = INT_COEF_MAX`, round, clip.\n",
        "3. Search the 3ᵏ neighbourhood around the rounded vector; pick min variance.\n",
        "4. Drop trivial cases (all-zero, single non-zero coefficient).\n",
        "5. Filter by **variance ratio** `c·G[S,S]·c / Σ cᵢ²·var(Pᵢ)` — small ratio = combination cancels much of individual variance, i.e. genuinely co-integrates.\n",
        "\n",
        "Inside a 5-product group all 26 subsets across k ∈ {2..5} are exhaustive — no sampling, no shortcuts.\n",
    ))

    cells.append(code(
        "def best_integer_combo(S):\n",
        "    Gs = G[np.ix_(S, S)]\n",
        "    eigvals, eigvecs = np.linalg.eigh(Gs)\n",
        "    v = eigvecs[:, 0]\n",
        "    if np.max(np.abs(v)) == 0:\n",
        "        return None, np.inf, np.inf\n",
        "    scale = INT_COEF_MAX / np.max(np.abs(v))\n",
        "    near = np.clip(np.round(v * scale).astype(int), INT_COEF_MIN, INT_COEF_MAX)\n",
        "    best_c, best_v = None, np.inf\n",
        "    for d in iproduct([-1, 0, 1], repeat=len(S)):\n",
        "        c = np.clip(near + np.array(d), INT_COEF_MIN, INT_COEF_MAX)\n",
        "        if (c == 0).all():\n",
        "            continue\n",
        "        if (c != 0).sum() < 2:\n",
        "            continue\n",
        "        v_combo = c @ Gs @ c\n",
        "        if v_combo < best_v:\n",
        "            best_v, best_c = v_combo, c.copy()\n",
        "    if best_c is None:\n",
        "        return None, np.inf, np.inf\n",
        "    norm_var = sum((best_c[i] ** 2) * var[S[i]] for i in range(len(S)))\n",
        "    var_ratio = float(best_v / max(norm_var, 1e-12))\n",
        "    return best_c, float(best_v), var_ratio\n",
        "\n",
        "\n",
        "pure_rows = []\n",
        "for k in range(2, P + 1):\n",
        "    for S in combinations(range(P), k):\n",
        "        S_l = list(S)\n",
        "        c_int, v_combo, vr = best_integer_combo(S_l)\n",
        "        if c_int is None:\n",
        "            continue\n",
        "        spread = X[:, S_l] @ c_int.astype(float)\n",
        "        pure_rows.append({\n",
        "            \"k\":                 k,\n",
        "            \"basket\":            [columns[s] for s in S_l],\n",
        "            \"int_coefs\":         [int(c) for c in c_int],\n",
        "            \"basket_str\":        fmt_basket([columns[s] for s in S_l], list(c_int.astype(float))),\n",
        "            \"max_abs_coef\":      int(max(abs(c) for c in c_int)),\n",
        "            \"combo_var\":         float(v_combo),\n",
        "            \"var_ratio\":         vr,\n",
        "            \"adf_p\":             adf_p(spread),\n",
        "            \"half_life\":         half_life(spread),\n",
        "        })\n",
        "pure_table = pd.DataFrame(pure_rows).sort_values([\"adf_p\", \"var_ratio\"]).reset_index(drop=True)\n",
        "pure_table.to_csv(OUT_DIR / \"pure_integer_combos.csv\", index=False)\n",
        "\n",
        "print(\"=== Pure integer combinations sorted by ADF p, then var_ratio ===\")\n",
        "display(pure_table.round(4))\n",
        "\n",
        "for k in sorted(pure_table[\"k\"].unique()):\n",
        "    sub = pure_table.query(\"k == @k\")\n",
        "    print(f\"\\nBest pure k={k} combo: {sub.iloc[0]['basket_str']}  \"\n",
        "          f\"(ADF p={sub.iloc[0]['adf_p']:.3g}, half-life={sub.iloc[0]['half_life']})\")\n",
    ))

    # ---- §13 dashboard ----
    cells.append(md(
        "## §13 — Dashboard + residual plots for the strongest results\n",
        "\n",
        "Compile one-line winners from §6, §7, §9, §10, §11, §12 into a single ranked shortlist, then plot residual time-series with ±2σ rolling band and z-score for the top entries. A clean tradeable spread shows many round-trips through the band; a single big move that never reverts is selection bias from running thousands of fits.\n",
    ))

    cells.append(code(
        "def plot_residual(name, series, window=WINDOW_FAST):\n",
        "    s = pd.Series(series).dropna()\n",
        "    rm = s.rolling(window).mean()\n",
        "    rs = s.rolling(window).std()\n",
        "    z  = (s - rm) / rs\n",
        "    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.08,\n",
        "                        subplot_titles=[f\"{name} — residual + ±2σ\", \"z-score\"])\n",
        "    fig.add_trace(go.Scatter(y=(rm + 2*rs).values, line=dict(width=0), showlegend=False), row=1, col=1)\n",
        "    fig.add_trace(go.Scatter(y=(rm - 2*rs).values, line=dict(width=0), fill=\"tonexty\",\n",
        "                             fillcolor=\"rgba(255,165,0,0.15)\", showlegend=False), row=1, col=1)\n",
        "    fig.add_trace(go.Scatter(y=s.values, line=dict(width=0.7, color=\"steelblue\"), name=\"resid\"), row=1, col=1)\n",
        "    fig.add_trace(go.Scatter(y=rm.values, line=dict(width=1.0, dash=\"dot\", color=\"orange\"),\n",
        "                             name=\"rolling mean\"), row=1, col=1)\n",
        "    fig.add_trace(go.Scatter(y=z.values, line=dict(width=0.7, color=\"purple\"), name=\"z\"), row=2, col=1)\n",
        "    fig.update_layout(height=480, hovermode=\"x unified\", showlegend=False, title=name)\n",
        "    fig.show()\n",
        "\n",
        "\n",
        "dashboard = []\n",
        "\n",
        "if len(pair_table):\n",
        "    r = pair_table.dropna(subset=[\"eg_p\"]).iloc[0]\n",
        "    dashboard.append({\"section\": \"§6 best OLS pair\",\n",
        "                      \"recipe\":  f\"{r['a']} − {r['hedge_ratio']:.3f}·{r['b']}\",\n",
        "                      \"p_value\": r[\"eg_p\"], \"half_life\": r[\"half_life\"]})\n",
        "\n",
        "if len(int_pair_table):\n",
        "    r = int_pair_table.dropna(subset=[\"int_adf_p\"]).iloc[0]\n",
        "    sign = \"−\" if r[\"int_h\"] > 0 else \"+\"\n",
        "    dashboard.append({\"section\": \"§7 best integer pair\",\n",
        "                      \"recipe\":  f\"{r['a']} {sign} {abs(r['int_h'])}·{r['b']}\",\n",
        "                      \"p_value\": r[\"int_adf_p\"], \"half_life\": r[\"int_half_life\"]})\n",
        "\n",
        "if len(idx_table):\n",
        "    r = idx_table.dropna(subset=[\"adf_p\"]).iloc[0]\n",
        "    dashboard.append({\"section\": \"§9 best product-vs-index residual\",\n",
        "                      \"recipe\":  f\"{r['product']} − ({r['intercept']:.2f} + {r['beta_to_index']:.3f}·index)\",\n",
        "                      \"p_value\": r[\"adf_p\"], \"half_life\": r[\"half_life\"]})\n",
        "\n",
        "for k, df in basket_results.items():\n",
        "    df_ok = df.dropna(subset=[\"adf_p\"])\n",
        "    if len(df_ok):\n",
        "        r = df_ok.iloc[0]\n",
        "        dashboard.append({\"section\": f\"§10 best continuous K={k}\",\n",
        "                          \"recipe\":  r[\"basket_str\"],\n",
        "                          \"p_value\": r[\"adf_p\"], \"half_life\": r[\"half_life\"]})\n",
        "\n",
        "for k, df in basket_int.items():\n",
        "    df_ok = df.dropna(subset=[\"int_adf_p\"])\n",
        "    if len(df_ok):\n",
        "        r = df_ok.iloc[0]\n",
        "        dashboard.append({\"section\": f\"§11 best integer K={k}\",\n",
        "                          \"recipe\":  r[\"int_basket_str\"],\n",
        "                          \"p_value\": r[\"int_adf_p\"], \"half_life\": r[\"int_half_life\"]})\n",
        "\n",
        "if len(pure_table):\n",
        "    for k in sorted(pure_table[\"k\"].unique()):\n",
        "        sub = pure_table.query(\"k == @k\").dropna(subset=[\"adf_p\"])\n",
        "        if len(sub):\n",
        "            r = sub.iloc[0]\n",
        "            dashboard.append({\"section\": f\"§12 best pure integer k={k}\",\n",
        "                              \"recipe\":  r[\"basket_str\"],\n",
        "                              \"p_value\": r[\"adf_p\"], \"half_life\": r[\"half_life\"]})\n",
        "\n",
        "dash_df = pd.DataFrame(dashboard).sort_values(\"p_value\").reset_index(drop=True)\n",
        "dash_df.to_csv(OUT_DIR / \"dashboard.csv\", index=False)\n",
        "print(\"=== Dashboard — winners by section, sorted by p-value ===\")\n",
        "display(dash_df.round(5))\n",
    ))

    cells.append(code(
        "# Plot the residual for the top 6 dashboard entries\n",
        "TOP_PLOTS = 6\n",
        "for _, row in dash_df.head(TOP_PLOTS).iterrows():\n",
        "    name = f\"{row['section']}: {row['recipe']}\"\n",
        "    # Reconstruct the residual\n",
        "    section = row[\"section\"]\n",
        "    series = None\n",
        "    if \"§6\" in section:\n",
        "        r = pair_table.dropna(subset=[\"eg_p\"]).iloc[0]\n",
        "        series = X[:, columns.index(r['a'])] - r['hedge_ratio'] * X[:, columns.index(r['b'])]\n",
        "    elif \"§7\" in section:\n",
        "        r = int_pair_table.dropna(subset=[\"int_adf_p\"]).iloc[0]\n",
        "        series = X[:, columns.index(r['a'])] - r['int_h'] * X[:, columns.index(r['b'])]\n",
        "    elif \"§9\" in section:\n",
        "        r = idx_table.dropna(subset=[\"adf_p\"]).iloc[0]\n",
        "        s = mid_aligned[r['product']].values\n",
        "        A_ = np.column_stack([np.ones_like(index_series.values), index_series.values])\n",
        "        coef, *_ = np.linalg.lstsq(A_, s, rcond=None)\n",
        "        series = s - A_ @ coef\n",
        "    elif \"§10\" in section:\n",
        "        k = int(section.split(\"K=\")[1])\n",
        "        r = basket_results[k].dropna(subset=[\"adf_p\"]).iloc[0]\n",
        "        series = reconstruct_residual(r['target_idx'], r['S_idx'], np.asarray(r['ols_beta']))\n",
        "    elif \"§11\" in section:\n",
        "        k = int(section.split(\"K=\")[1])\n",
        "        r = basket_int[k].dropna(subset=[\"int_adf_p\"]).iloc[0]\n",
        "        S_idx = [columns.index(b) for b in r['basket']]\n",
        "        c_int = np.asarray(r['int_coefs'], dtype=float)\n",
        "        series = X[:, columns.index(r['target'])] - X[:, S_idx] @ c_int\n",
        "    elif \"§12\" in section:\n",
        "        k = int(section.split(\"k=\")[1])\n",
        "        r = pure_table.query(\"k == @k\").dropna(subset=[\"adf_p\"]).iloc[0]\n",
        "        S_idx = [columns.index(b) for b in r['basket']]\n",
        "        c_int = np.asarray(r['int_coefs'], dtype=float)\n",
        "        series = X[:, S_idx] @ c_int\n",
        "    if series is not None:\n",
        "        plot_residual(name, series, window=WINDOW_FAST)\n",
    ))

    # ---- §14 how to read ----
    cells.append(md(
        "## §14 — How to read these results\n",
        "\n",
        f"Every CSV is in `{out_dir}/`:\n",
        "\n",
        "- `pair_correlations.csv` — Pearson + Spearman + Kendall for all 10 pairs.\n",
        "- `rolling_correlation_summary.csv` — stability of return correlation per pair.\n",
        "- `leadlag_summary.csv` — peak cross-correlation lag per pair.\n",
        "- `pair_cointegration.csv` — all 10 pairs with EG / ADF / half-life.\n",
        "- `pair_integer_hedge.csv` — same pairs after integer hedge fitting.\n",
        "- `pca_residuals.csv` — variance explained + ADF on each PC's residual.\n",
        "- `group_index.csv`, `product_vs_index.csv` — composite index + per-product residual stats.\n",
        "- `basket_continuous_K{k}.csv` — top continuous baskets per K.\n",
        "- `basket_integer_K{k}.csv` — top integer baskets per K (the main output).\n",
        "- `pure_integer_combos.csv` — pure integer combinations from eigenvector search.\n",
        "- `dashboard.csv` — one-line winners per section.\n",
        "\n",
        "### Triage rules (within a tightly-correlated group)\n",
        "\n",
        "1. **Distrust strong level-correlation alone.** Within a group everything will look highly correlated at the level. Look at `pearson_ret`, `int_adf_p`, and the residual plot.\n",
        "2. **Filter `adf_p < 0.05`** — those are statistically mean-reverting after the search-over-many cost.\n",
        "3. **Filter `half_life ∈ [50, 500]`** — fast enough to round-trip in a round, slow enough to clear costs.\n",
        "4. **Filter `int_resid_inflation < 1.10`** in §11 — integer rounding cost should be small.\n",
        "5. **Prefer `max_abs_coef ≤ 3`** — position limit is 10, so a max coef of 3 lets you trade up to ~3 units of the basket at full size on the dominant leg.\n",
        "6. **Eyeball the residual plot.** A real edge has many round-trips through ±2σ. One big move that never reverts is selection bias.\n",
        "\n",
        "### What's special about within-group results\n",
        "\n",
        "- §8 (PCA) tells you whether the group is essentially one factor (PC1 dominates ⇒ the only edge is variant-level relative value) or genuinely multi-factor (multiple PCs explain meaningful variance ⇒ richer structure).\n",
        "- §9 (product-vs-index) is the cleanest ‘structural’ trade in the group: each product against the average of its peers. If only one product has a stationary residual, that's a strong signal — the others all swim with the school.\n",
        "- §11 / §12 baskets that beat §7's integer pairs justify the extra complexity. If they don't, stick with the pair.\n",
        "\n",
        "### Re-run knobs\n",
        "\n",
        "- Tighten `INT_COEF_MAX` to 3 for stricter ‘cheap’ baskets.\n",
        "- Widen `MAX_LAG_LEAD` if §5 shows the peak at the boundary (means longer lead is plausible).\n",
        "- Set `SUBSAMPLE_FOR_ADF=None` for full-precision ADF on the final shortlist.\n",
    ))

    return cells


def build_notebook(group_key: str, cfg: dict) -> dict:
    return {
        "cells": build_cells(group_key, cfg),
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


if __name__ == "__main__":
    for key, cfg in GROUPS.items():
        nb = build_notebook(key, cfg)
        path = ROOT / cfg["filename"]
        path.write_text(json.dumps(nb, indent=1))
        print(f"Wrote {path} ({len(nb['cells'])} cells)")
